### ISSUE TITLE
Symbols broken on kicad 5.0.0

### ISSUE THREAD

**Issue by jschall** [mwelling/pocketbone-kicad#3]
On opening the schematic, I get a message about missing libraries: device.lib transistors.lib and so on (many of them). When I click ok, it asks about remapping symbols. If I click ok, the schematic opens with broken symbols. If I click cancel, the schematic opens correctly. If I then save the schematic, I get a message saying that it failed to properly save a file /home/jschall/pocketbone-kicad/pocketbone-kicad-cache.lib and then the symbols become broken again.

**Comment by mwelling** [comment]
I will look into converting the design to KiCAD 5.0. Have been using 5 for a while now just haven't touched this project in a while.

I will update this ticket when it is ready.

**Comment by mwelling** [comment]
There were some hiccups on conversion to say the least. Please checkout the kicad5 branch to see if it works for you.
